server:
  port: 9002

spring:
  application:
    name: project-manager-api-local

  # [JPA]
  jpa:
    hibernate:
      ddl-auto: create-drop

# [jwt]
jwt:
  signature: local-signature-key
  issuer: me.whypie.authorization
  subject: resource-access
  audience: test-client
  access-token-validity-in-seconds-term: 600 # access token의 유효 기간 : 10분
  refresh-token-validity-in-seconds-term: 1200 # refresh token의 유효 기간 : 20분

# [Eureka]
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

# [Spring Boot Actuator]
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always